### ISSUE TITLE
data not comming

### ISSUE THREAD

**Issue by zzzzz-attachment** [MythicStack/whoisrecon#1]
![image](https://github.com/MythicStack/whoisrecon/assets/131388582/9b406e41-700b-4284-baa1-42f2bdfebd48)

**Comment by MythicStack** [comment]
I've gone through and tested several aspects to recreate the issue and I was able to do so in several different ways.

Firstly, if the domain is no longer registered the output will be more clear about that. Second, there are some domain TLDs that say they're supported by the WHOIS package, but return null information when the registrar is queried: 

```
Error trying to connect to socket: closing socket - timed out
{
  "domain_name": null,
  "registrar": null,
  "whois_server": null,
  "referral_url": null,
  "updated_date": null,
  "creation_date": null,
  "expiration_date": null,
  "name_servers": null,
  "status": null,
  "emails": null,
  "dnssec": null,
  "name": null,
  "org": null,
  "address": null,
  "city": null,
  "state": null,
  "registrant_postal_code": null,
  "country": null
}
```

I'm unable to completely resolve it on my end, I'll look into contributing to that project in an effort to resolve there. In the meantime, I've created [Release v0.1.2](https://github.com/MythicStack/whoisrecon/releases/tag/v0.1.2) to mitigate this with updated output.
